version: "3"

services:
  mongodb:
    container_name: "grpc-golang-master-class-build-modern-api-and-microservices"
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
volumes:
  mongodb-data:
  # redis-data: